spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springjpa
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
management:
  endpoints:
     web:
       exposure:
         include: "*"
         exclude: "env,beans"